label: 'Expiration du mot de passe'
description: "Contrôle si l'utilisateur doit réinitialiser son mot de passe. Si le mot de passe a expiré, ce champ est automatiquement coché après l'exécution du planificateur de tâches (cron)."
settings:
  on_label: 'Mot de passe expiré'
  off_label: 'Mot de passe non expiré'
