_core:
  default_config_hash: 4GIX5Esnc_umpXUBj4IIocRX7Mt5fPhm4AgXfE3E56E
module:
  address: 0
  announcements_feed: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breadcrumb_extra_field: 0
  breakpoint: 0
  ckeditor5: 0
  comment: 0
  config: 0
  config_translation: 0
  contextual: 0
  datetime: 0
  dblog: 0
  default_content: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  entity: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  gin_login: 0
  gin_toolbar: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  jquery_ui: 0
  jquery_ui_autocomplete: 0
  jquery_ui_menu: 0
  language: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  locale: 0
  login_emailusername: 0
  mailsystem: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  module_filter: 0
  mysql: 0
  navigation: 0
  navigation_extra_tools: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs_features: 0
  password_policy_character_types: 0
  password_policy_characters: 0
  password_policy_history: 0
  password_policy_length: 0
  password_policy_username: 0
  path: 0
  path_alias: 0
  profile: 0
  robotstxt: 0
  search_api: 0
  search_api_solr: 0
  search_api_solr_admin: 0
  shortcut: 0
  shs: 0
  symfony_mailer_lite: 0
  system: 0
  taxonomy: 0
  taxonomy_manager: 0
  telephone: 0
  term_reference_tree: 0
  text: 0
  token: 0
  ultimate_cron: 0
  update: 0
  user: 0
  views_ui: 0
  pathauto: 1
  password_policy: 10
  views: 10
  paragraphs: 11
  paragraphs_ee: 15
  standard: 1000
theme:
  olivero: 0
  claro: 0
  gin: 0
  stable9: 0
profile: standard
