_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
theme: current
defaults:
  sender: SMTPMailSystem
  formatter: symfony_mailer_lite
modules:
  symfony_mailer_lite:
    none:
      sender: SMTPMailSystem
      formatter: symfony_mailer_lite
