_core:
  default_config_hash: JqYNByWeXZGynyqoPRWQIjp3VcQhuoyq5WlM-7YzBvI
langcode: fr
smtp_on: false
smtp_host: ssl0.ovh.net
smtp_hostbackup: ''
smtp_port: '465'
smtp_protocol: ssl
smtp_autotls: true
smtp_timeout: 30
smtp_username: jffranck@zlika.com
smtp_password: M480!t3m4!l
smtp_from: no-reply@ludosport.paris.zlika.com
smtp_fromname: 'Ludosport Paris'
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: true
smtp_test_address: jeff@zlika.com
smtp_reroute_address: ''
smtp_debugging: false
smtp_debug_level: 1
prev_mail_system: php_mail
smtp_keepalive: false
