_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: fr
uuid: e6be3fd6-f37d-4172-87e5-d737b389854a
name: 'Ludosport Paris'
mail: admin@ludosport.paris
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: fr
mail_notification: no-reply@ludosport.paris
