name: ludosport-paris

services:

  web:
    image: ghcr.io/ludosport-paris/web:main
    container_name: ludosport_web
    pull_policy: always
    ports:
      - 80:80
    environment:
      - FQDN  
    volumes:
      - drupal_public_files:/var/local/drupal/files:ro
    restart: always
    networks:
      - ludosport
      - proxy
    depends_on:
      php-fpm:
        condition: service_healthy

  php-fpm:
    image: ghcr.io/ludosport-paris/php-fpm:main
    container_name: ludosport_php_fpm
    pull_policy: always
    environment:
      - APP_ENV
      - DBNAME
      - USERNAME
      - PASSWORD
      - HOST
      - PORT
      - HASH_SALT
      - FQDN
    volumes:
      - drupal_public_files:/var/local/drupal/files
      - drupal_private_files:/var/local/drupal/private
    restart: always
    networks:  
      - ludosport
    depends_on:
      mariadb:
        condition: service_healthy
      solr:
        condition: service_started
      
  mariadb:
    image: mariadb:11.8
    container_name: ludosport_db
    pull_policy: always
    environment:
      - MARIADB_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MARIADB_USER=${USERNAME}
      - MARIADB_PASSWORD=${PASSWORD}
      - MARIADB_DATABASE=${DBNAME}
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    networks:
      - ludosport
    healthcheck:
      test: ["CMD", "mariadb", "-u${USERNAME}", "-p${PASSWORD}", "-e", "use ${DBNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  solr:
    image: solr:9
    container_name: ludosport_solr
    pull_policy: always
    ports:
      - 8983:8983
    volumes:
      - solr_data:/var/solr
    command:
      - solr-precreate
      - ludosport  
    environment:
      - SOLR_MODULES=analysis-extras,ltr,langid,extraction
    restart: always
    networks:
      - ludosport
      
volumes:
  mariadb_data:
    external: true
    name: ludosport_db_data
  drupal_public_files:
    external: true
    name: ludosport_public_files
  drupal_private_files:
    external: true
    name: ludosport_private_files
  solr_data:
    external: true
    name: ludosport_solr_data

networks:
  ludosport:
    external: true
    name: ludosport
  proxy:
    external: true
    # Traefik network
    name: services