FROM php:8.3-fpm-alpine

# Install packages
RUN apk add --no-cache \
    bash \
    freetype-dev \
    git \
    icu-dev \
    jpeg-dev \
    libavif-dev \
    libpng-dev \
    libwebp-dev \
    libzip-dev \
    mysql-client \
    sudo \
    unzip

# Install the PHP zip extention
RUN docker-php-ext-install zip

# Install the PHP intl extention
RUN docker-php-ext-configure intl
RUN docker-php-ext-install intl

# Install the PHP mysqli extention
RUN docker-php-ext-install mysqli

# Install the PHP pdo_mysql extention
RUN docker-php-ext-install pdo_mysql

# Install the PHP gd library
RUN docker-php-ext-install gd && \
    docker-php-ext-configure gd --with-freetype --with-jpeg --with-avif --with-webp && \
    docker-php-ext-install gd

# Install composer and add its bin to the PATH.
RUN curl -s http://getcomposer.org/installer | php && \
    mv composer.phar /usr/local/bin/composer

# Création des volumes
RUN mkdir /var/local/drupal
VOLUME [ "/var/local/drupal/www", "/var/local/drupal/files", "/var/local/drupal/private" ]

# Copie du script de déploiement Drupal
COPY ./deploy /var/local/drupal/
RUN chmod u+x /var/local/drupal/deploy

# Add drush symbolic link
RUN ln -fs /var/local/drupal/www/current/vendor/bin/drush /usr/local/bin/drush

WORKDIR /var/local/drupal