#!/bin/sh

WWW_USER=www-data

if id deploy >/dev/null 2>&1; then
    DEPLOY_USER=deploy
else
    DEPLOY_USER=root
fi


# Change owner group of all application assets
chown -R ${DEPLOY_USER}:${WWW_USER} /var/www/ludosport
chown -R ${DEPLOY_USER}:${WWW_USER} /var/local/settings.php
chown -R ${DEPLOY_USER}:${WWW_USER} /var/local/files
chown -R ${DEPLOY_USER}:${WWW_USER} /var/local/private

# Create settings.php symbolic link
ln -fs /var/local/settings.php /var/www/ludosport/web/sites/default/settings.php

# Manage file permissions
find /var/www/ludosport/web -type d -exec chmod u=rwx,g=rx,o= '{}' \;
find /var/www/ludosport/web -type f -exec chmod u=rw,g=r,o= '{}' \;
ln -fs /var/local/files /var/www/ludosport/web/sites/default/files
chmod -R ug=rwx,o= /var/www/ludosport/web/sites/default/files
chmod -R ug=rwx,o= /var/local/private
find /var/www/ludosport/web/sites/default/files -type f -exec chmod ug=rw,o= '{}' \;
find /var/local/private -type f -exec chmod ug=rw,o= '{}' \;

# Add drush symbolic link
ln -fs /var/www/ludosport/vendor/bin/drush /usr/local/bin/drush

if [[ "$APP_ENV" = "local" ]]; then
    echo "No deploy on local env."
else
    # Composer install
    sudo -E -u ${DEPLOY_USER} composer install --no-dev

    # Cache clear
    sudo -E -u ${WWW_USER} drush cr

    # DB Update
    sudo -E -u ${WWW_USER} drush updb -y

    # Import configs
    sudo -E -u ${WWW_USER} bash -c "drush cim -y > /dev/null || drush cim -y"
fi

# Launch initial CMD
exec "php-fpm"